[package]
name = "merkle_tree"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
num = "0.4.3"
plonky2 = "0.2.2"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
