[package]
name = "fibonacci"
version = "0.1.0"
edition = "2021"

[dependencies]
"plonky2" = { version = "0.2.2" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
