edition = "2021"
tab_spaces = 4
newline_style = "Unix"
use_try_shorthand = true
use_field_init_shorthand = true
reorder_imports = true
imports_granularity = "Crate"
use_small_heuristics = "Max"
comment_width = 80
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100