[package]
name = "fibonacci-circuit"
version = "0.1.0"
edition = "2021"

[dependencies]
hashbrown = "0.14.5"
"plonky2" = { version = "0.2.0" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
