[package]
name = "sindri-script"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
dotenvy = "0.15.7"
sindri = "0.1.0"
tokio = { version = "1.37.0", features = ["full"] }
serde_json = "1.0.124"
tar = "0.4.41"
flate2 = "1.0.31"
reqwest = "0.12.5"
